### ISSUE TITLE
`TodoList`에서 search 누르지 않고 바로 결과 보여주기

### ISSUE THREAD

**Issue by naninyang** [grotesq/codelab-react-native-6th#1]
2021년 8월 21일 강좌분 `TodoList`에서 질문이 있습니다.
키워드를 입력하고 검색 버튼(`search`)을 누르면 주소와 우편번호가 뜨는데 키워드 입력하지 않고 바로 결과가 뜨게 처리하려면 어떻게 하면 될까요?
코드상에 직접 키워드를 삽입했다는 가정하에요.

이를테면 찾으려는 키워드가 '신사동'이라고 한다면 '신사동'을 `ZipCodeFinder.js`에 직접 넣어서 키워드 입력란과 검색 버튼 없는 상태에서 바로 목록을 뜨게 처리하고 싶다면 어떻게 코드를 수정하면 될까요?

**Comment by unk** [comment]
제가 답변이 좀 늦었네요.
TextInput의 onChangeText 에서 검색 API를 호출하도록 하면 될 것 같습니다.
다만 이런 경우 API 호출이 과도하게 일어날 수 있습니다.

1. API 호출에 대한 debounce 처리
2. 이미 호출했던 결과에 대한 캐싱 처리

같은 것들로 보완할 수 있을 것 같습니다.
